# Generated by Django 5.2.9 on 2026-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_git_link_user_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('S', 'Student'), ('I', 'Instructor')], default='S', max_length=1),
        ),
    ]
