# Generated by Django 6.0 on 2026-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('I', 'Instructor'), ('S', 'Student')], default='S', max_length=1),
        ),
    ]
