# Generated by Django 6.0 on 2026-02-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload Video File', null=True, upload_to='course_videos/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('A', 'Assessment_URL'), ('V', 'Video_URL'), ('D', 'Document')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube/Video Link', null=True),
        ),
    ]
